import "OpDatWRC.idl";

namespace MiniEditor
{
	[default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        void AddOp(String name, Int32 op);
        Windows.Foundation.Collections.IVectorView<OpDatWRC> GetOps();
    }
}
